# uwsgi configuration file for keyform
[uwsgi]
##### Django-related settings #####
# the base directory (full path)
chdir           = /app
# Django's wsgi file
wsgi-file       = keyformproject/wsgi.py


##### Process-related settings #####
project     = %n
# user id
uid             = 33
# group id
gid             = 33
# Spawn a master process to allow graceful restart
master          = true
# number of processes
workers         = 2
# number of threads
threads         = 16
# thundering herd avoidance
thunder-lock    = true
# error log
log-master      = true
# communication socket between http server and uwsgi
http-socket     = 0.0.0.0:8000
# ... with appropriate permissions - may be needed
chmod-socket    = 664 
# clear environment on exit
vacuum          = true
# increase buffer size to avoid the "invalid request block size" error
buffer-size     = 65535
# listen to sigterm for fast exit
die-on-term = true
