# uwsgi configuration file for keyform
[uwsgi]



##### Django-related settings #####
# the base directory (full path)
chdir           = /projects/keyformproject
# Django's wsgi file
wsgi-file       = keyformproject/wsgi.py
# the virtualenv (full path)
home            = /home/administrator/.virtualenvs/keyformproject



##### Process-related settings #####
project     = %n
# which uwsgi interface
#plugins     = python
# user id
uid             = 33
# group id
gid             = 33
# Spawn a master process to allow graceful restart
master          = true
# number of processes
workers         = 2
# number of threads
threads         = 16
# thundering herd avoidance
thunder-lock    = true
# error log
logto           = /var/log/uwsgi/%n.log
# communication socket between nginx and uwsgi
socket          = /projects/sock/%n.sock
# ... with appropriate permissions - may be needed
chmod-socket    = 664 
# clear environment on exit
vacuum          = true
# increase buffer size to avoid the "invalid request block size" error
buffer-size     = 65535
