# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-02-24 22:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_core_number', models.CharField(max_length=35)),
                ('key_type', models.CharField(choices=[('rm', 'Room/Apt.'), ('mb', 'Mailbox'), ('ot', 'Other (Specify)')], max_length=2)),
                ('room_number', models.CharField(max_length=42)),
                ('lost_key_number', models.CharField(max_length=24)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=128)),
                ('reason_for_request', models.CharField(choices=[('bk', 'Broken Key'), ('sk', 'Stolen Key'), ('wk', 'Worker Key')], max_length=2)),
                ('amt_recieved', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('paid_by', models.CharField(choices=[('ca', 'Cash'), ('ch', 'Check')], max_length=2)),
                ('charge_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('bpn', models.CharField(max_length=9)),
                ('created_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('charged_on_rcr', models.BooleanField(default=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyform.Building')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='keydata',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyform.Request'),
        ),
        migrations.AddField(
            model_name='comment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyform.Request'),
        ),
    ]
