# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-10 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('ca', 'Cash'), ('ch', 'Check')], max_length=2, null=True),
        ),
    ]
