# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-03 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pr', 'Processing'), ('ks', 'Key Sent'), ('kd', 'Key Distributed')], default='pr', max_length=2),
        ),
    ]
