# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-24 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0002_auto_20170310_1918'),
        ('keyform', '0002_request_status'),
    ]

    operations = [
    ]
