# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0003_merge_20170324_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=75)),
            ],
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='request',
            name='locksmith_email_sent',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='request',
            name='previous_status',
            field=models.CharField(choices=[('pr', 'Processing'), ('ks', 'Key Sent'), ('kd', 'Key Distributed')], default='pr', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='updated',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='contact',
            name='building',
            field=models.ManyToManyField(to='keyform.Building'),
        ),
    ]
