# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0004_auto_20170515_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keydata',
            old_name='new_core_number',
            new_name='core_number',
        ),
    ]
