# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0004_auto_20170515_1622'),
        ('keyform', '0004_auto_20170526_2048'),
    ]

    operations = [
    ]
