# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0005_auto_20170620_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keydata',
            old_name='lost_key_number',
            new_name='key_number',
        ),
    ]
