# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0005_merge_20170531_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=75),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='locksmith_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='updated',
            field=models.BooleanField(default=True),
        ),
    ]
