# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0006_auto_20170621_0042'),
        ('keyform', '0006_auto_20170622_0116'),
    ]

    operations = [
    ]
