# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0007_auto_20170718_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
