# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0007_merge_20170626_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('pr', 'Processing'), ('ks', 'Key Sent'), ('kd', 'Key Distributed'), ('rc', 'Request Cancelled')], default='pr', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='request',
            name='previous_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_status', to='keyform.Status'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='keyform.Status'),
        ),
        migrations.AddField(
            model_name='contact',
            name='alert_statuses',
            field=models.ManyToManyField(to='keyform.Status'),
        ),
    ]
