# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0008_auto_20170705_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
