# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 18:40
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0008_auto_20170727_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keydata',
            name='core_number',
            field=models.CharField(blank=True, max_length=35, verbose_name='New Core Number'),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='key_number',
            field=models.CharField(max_length=24, verbose_name='Lost/Stolen/Damaged Key Number'),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='request',
            name='charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='request',
            name='payment_method',
            field=models.CharField(choices=[('ca', 'Cash'), ('ch', 'Check'), ('na', 'Not Applicable')], default='na', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Staff member completing request'),
        ),
    ]
