# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0009_auto_20170705_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['order'], 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('pr', 'Processing'), ('ks', 'Key Sent'), ('kd', 'Key Distributed'), ('rc', 'Request Cancelled')], default='pr', max_length=2),
        ),
    ]
