# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0009_auto_20170804_1840'),
        ('keyform', '0009_building_deleted'),
    ]

    operations = [
    ]
