# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0010_auto_20170811_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='payment_method',
            field=models.CharField(choices=[('ca', 'Cash'), ('ch', 'Check'), ('na', 'Not Applicable')], max_length=2),
        ),
    ]
