# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0011_auto_20170914_1601'),
        ('keyform', '0010_merge_20170918_1735'),
    ]

    operations = [
    ]
