# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-10 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0012_merge_20171005_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('hide_core_number', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='keydata',
            name='new_key_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keyform.KeyType'),
        ),
    ]
