# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 16:27
from __future__ import unicode_literals

from django.db import migrations

def convert_names(apps, schema_editor):
    contacts = apps.get_model('keyform', 'Contact')

    for contact in contacts.objects.all():
        contact.email = contact.email.lower()
        contact.save()

class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0013_auto_20180304_2240'),
    ]

    operations = [
        migrations.RunPython(convert_names, migrations.RunPython.noop)
    ]
