# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-05 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0015_auto_20180304_2002'),
        ('keyform', '0014_auto_20180305_1627'),
    ]

    operations = [
    ]
