# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-08 14:59
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0016_merge_20180305_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bill to Account:'),
        ),
        migrations.AlterField(
            model_name='request',
            name='reason_for_request',
            field=models.CharField(choices=[('dk', 'Damaged Key'), ('lk', 'Lost/Stolen Key'), ('sk', 'Staff File Key')], max_length=2, verbose_name='Request for:'),
        ),
    ]
