# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-07-18 19:20
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0017_auto_20180308_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keydata',
            name='quantity',
            field=models.IntegerField(help_text="If you don't need to order more keys because there are enough already, you can mark zero.", validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity to Order'),
        ),
        migrations.AlterField(
            model_name='request',
            name='amt_received',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount received'),
        ),
    ]
