# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-07-23 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyform', '0018_auto_20250718_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_timestamp'], 'permissions': [('can_charge_zero', 'Can submit a form with zero charge amount')]},
        ),
    ]
